# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile/produceurl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protofile/produceurl.proto',
  package='produceurl',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aprotofile/produceurl.proto\x12\nproduceurl\"\x19\n\nUrlRequest\x12\x0b\n\x03req\x18\x01 \x01(\t\"\x1a\n\x0bUrlResponse\x12\x0b\n\x03url\x18\x01 \x03(\t2J\n\nProduceUrl\x12<\n\x07SendUrl\x12\x16.produceurl.UrlRequest\x1a\x17.produceurl.UrlResponse\"\x00\x62\x06proto3'
)




_URLREQUEST = _descriptor.Descriptor(
  name='UrlRequest',
  full_name='produceurl.UrlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='produceurl.UrlRequest.req', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=67,
)


_URLRESPONSE = _descriptor.Descriptor(
  name='UrlResponse',
  full_name='produceurl.UrlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='produceurl.UrlResponse.url', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['UrlRequest'] = _URLREQUEST
DESCRIPTOR.message_types_by_name['UrlResponse'] = _URLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UrlRequest = _reflection.GeneratedProtocolMessageType('UrlRequest', (_message.Message,), {
  'DESCRIPTOR' : _URLREQUEST,
  '__module__' : 'protofile.produceurl_pb2'
  # @@protoc_insertion_point(class_scope:produceurl.UrlRequest)
  })
_sym_db.RegisterMessage(UrlRequest)

UrlResponse = _reflection.GeneratedProtocolMessageType('UrlResponse', (_message.Message,), {
  'DESCRIPTOR' : _URLRESPONSE,
  '__module__' : 'protofile.produceurl_pb2'
  # @@protoc_insertion_point(class_scope:produceurl.UrlResponse)
  })
_sym_db.RegisterMessage(UrlResponse)



_PRODUCEURL = _descriptor.ServiceDescriptor(
  name='ProduceUrl',
  full_name='produceurl.ProduceUrl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=97,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendUrl',
    full_name='produceurl.ProduceUrl.SendUrl',
    index=0,
    containing_service=None,
    input_type=_URLREQUEST,
    output_type=_URLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCEURL)

DESCRIPTOR.services_by_name['ProduceUrl'] = _PRODUCEURL

# @@protoc_insertion_point(module_scope)
