# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protofile import produceurl_pb2 as protofile_dot_produceurl__pb2


class ProduceUrlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendUrl = channel.unary_unary(
                '/produceurl.ProduceUrl/SendUrl',
                request_serializer=protofile_dot_produceurl__pb2.UrlRequest.SerializeToString,
                response_deserializer=protofile_dot_produceurl__pb2.UrlResponse.FromString,
                )


class ProduceUrlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProduceUrlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUrl,
                    request_deserializer=protofile_dot_produceurl__pb2.UrlRequest.FromString,
                    response_serializer=protofile_dot_produceurl__pb2.UrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'produceurl.ProduceUrl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProduceUrl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/produceurl.ProduceUrl/SendUrl',
            protofile_dot_produceurl__pb2.UrlRequest.SerializeToString,
            protofile_dot_produceurl__pb2.UrlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
